// EPISODE DATA
// ============================================================
const EP_TITLES_N = {
  1:'Enter: Naruto Uzumaki!', 2:'My Name is Konohamaru!', 3:'Sasuke and Sakura: Friends or Foes?',
  4:'Pass or Fail: Survival Test', 5:'You Failed! Kakashi\'s Final Decision', 6:'A Dangerous Mission!',
  7:'The Assassin of the Mist!', 8:'The Oath of Pain', 9:'Kakashi: Sharingan Warrior!',
  10:'The Forest of Chakra', 11:'The Land Where a Hero Once Lived', 12:'Battle on the Bridge! Zabuza Returns!',
  13:'Haku\'s Secret Jutsu: Crystal Ice Mirrors', 14:'The Number One Hyperactive, Knucklehead Ninja Joins the Fight!!',
  15:'Zero Visibility: The Sharingan Shatters', 16:'The Broken Seal', 17:'White Past: Hidden Ambition',
  18:'The Weapons Known as Shinobi', 19:'The Demon in the Snow',
  20:'A New Chapter Begins: The Chunin Exam!', 21:'Identify Yourself: Powerful New Rivals', 22:'Chunin Challenge: Rock Lee vs. Sasuke!',
  23:'Genin Takedown! All Nine Rookies Face Off!', 24:'Start Your Engines: The Chunin Exam Begins!',
  25:'The Tenth Question: All or Nothing!', 26:'Special Report: Live from the Forest of Death!',
  27:'The Chunin Exam Stage 2: The Forest of Death', 28:'Eat or Be Eaten: Panic in the Forest',
  29:'Naruto\'s Counterattack: Never Give In!', 30:'The Sharingan Revived: Dragon-Flame Jutsu!',
  31:'Bushy Brow\'s Jutsu: Sasuke Style!', 32:'Sakura Blossoms!', 33:'Battle Formation: Ino-Shika-Cho!',
  34:'Akamaru Trembles: Gaara\'s Cruel Strength!', 35:'The Scroll\'s Secret: No Peeking Allowed',
  36:'Clone vs. Clone: Mine are Better than Yours!', 37:'Surviving the Cut! The Rookie Nine Together Again!',
  38:'Narrowing the Field: Sudden Death Elimination!', 39:'Bushy Brow\'s Jealousy: Lions Barrage Unleashed!',
  40:'Kakashi and Orochimaru: Face-to-Face!', 41:'Rivals: Spoiling Each Other\'s Fun',
  42:'The Ultimate Battle: Cha!', 43:'Killer Kunoichi and a Shaky Shikamaru', 44:'Akamaru Unleashed! Who\'s Top Dog Now?',
  45:'Surprise Attack! Naruto\'s Secret Weapon!', 46:'Byakugan Battle: Hinata Grows Bold!',
  47:'A Failure Stands Tall!', 48:'Gaara vs. Rock Lee: The Power of Youth Explodes!',
  49:'Lee\'s Hidden Strength: Forbidden Secret Jutsu!', 50:'The Fifth Gate: A Splendid Ninja is Born',
  51:'A Shadow in Darkness: Danger Approaches Sasuke', 52:'The Chunin Exam Begins!',
  53:'Long Time No See: Jiraiya Returns!', 54:'The Summoning Jutsu: Wisdom of the Toad Sage!',
  55:'A Feeling of Yearning, a Flower Full of Hope', 56:'Live or Die! Risk It All to Win It All!',
  57:'He Flies! He Jumps! He Lurks! Chief Toad Appears!', 58:'Hospital Besieged: The Evil Hand Revealed!',
  59:'The Final Rounds: Rush to the Battle Arena!', 60:'Byakugan vs. Shadow Clone Jutsu!',
  61:'Ultimate Defense: Zero Blind Spot!', 62:'A Failure\'s True Power', 63:'Hit It or Quit It: The Final Rounds Begin!',
  64:'Zero Motivation: The Guy with Cloud Envy!', 65:'Dancing Leaf, Squirming Sand',
  66:'Too Late for Help', 67:'Late for the Show, but Ready to Fight: Naruto vs. Sasuke!',
  68:'Zero Hour! The Destruction of the Hidden Leaf Village Begins!', 69:'Village in Distress: A New A-Ranked Mission!',
  70:'A Shirker\'s Call to Action: A Layabout No More!', 71:'An Unrivaled Match: Hokage Battle Royale!',
  72:'A Mistake from the Past: A Face Revealed!', 73:'Forbidden Secret Technique: Reaper Death Seal!',
  74:'Astonishing Truth! Gaara\'s Identity Emerges!', 75:'Sasuke\'s Decision: Pushed to the Edge!',
  76:'Assassin of the Moonlit Night', 77:'Light vs. Dark: The Two Faces of Gaara',
  78:'Explosion! These Are the Naruto!', 79:'Beyond the Limit of Darkness and Light',
  80:'The Third Hokage, Forever...',
  81:'Return of the Morning Mist', 82:'Eye to Eye: Sharingan vs. Sharingan!',
  83:'Jiraiya: Naruto\'s Potential Disaster!', 84:'Inner Sakura\'s Hostility: The Enter Intruders!',
  85:'Hate Among the Uchihas: The Last of the Clan!', 86:'Training Begins: I Will Be Strong!',
  87:'Keep on Training: Pop Goes the Water Balloon!', 88:'Focal Point: The Mark of the Leaf',
  89:'An Impossible Choice: The Pain Within Tsunade\'s Heart', 90:'Unforgivable! A Total Lack of Respect!',
  91:'Kidnapped! Naruto\'s Hot Spring Adventure!', 92:'Whirlpool of Emotions! What Will Happen to Hinata?',
  93:'Hot-Blooded Confrontation: Student vs. Sensei', 94:'Eat or Die! Mushrooms from Hell!',
  95:'The Third Everyone\'s Memories', 96:'Deadlock! Sannin Showdown!',
  97:'Kidnapped! Naruto\'s Hot Spring Adventure!', 98:'Tsunade\'s Determination',
  99:'The Will of Fire Still Burns!', 100:'Sensei and Student: The Bond of the Shinobi',
  101:'Want to Look, Know and Confirm Kakashi-Sensei\'s Face',
  102:'Mission: Help an Old Friend in the Land of Tea', 103:'The Race Is On! Trouble on the High Seas!',
  104:'Run Idate Run! Nagi Island Awaits!', 105:'A Fierce Battle of Rolling Thunder!',
  106:'The Last Leg: A Final Act of Desperation',
  107:'The Battle Begins: Naruto vs. Sasuke', 108:'Bitter Rivals and Broken Bonds',
  109:'An Invitation from the Sound', 110:'Formation! The Sasuke Retrieval Squad!',
  111:'Sound vs. Leaf', 112:'Squad Mutiny: Everything Falls Apart!',
  113:'Full Throttle Power! Choji, Ablaze!', 114:'Goodbye Old Friend...! I\'ll Always Believe in You!',
  115:'Your Opponent is Me!', 116:'360 Degrees of Vision: The Byakugan\'s Blind Spot!',
  117:'Losing is Not an Option!', 118:'The Vessel Arrives Too Late',
  119:'Miscalculation: A New Enemy Appears!', 120:'Roar and Howl! The Ultimate Tag-Team!',
  121:'To Each His Own Battle', 122:'Fakeout: Shikamaru\'s Comeback!',
  123:'The Leaf\'s Handsome Devil!', 124:'The Beast Within', 125:'The Sand Shinobi: Allies of the Leaf',
  126:'Showdown: Gaara vs. Kimimaro!', 127:'Vengeful Strike! The Brazen Blade!',
  128:'A Cry on Deaf Ears', 129:'Brothers: Distance Among the Uchiha',
  130:'Father and Son, the Broken Crest', 131:'The Secrets of the Mangekyō Sharingan!',
  132:'For a Friend', 133:'A Plea from a Friend', 134:'The End of Tears',
  135:'The Promise That Could Not Be Kept',
  136:'Deep Cover?! A Super S-Ranked Mission!', 137:'A Town of Outlaws: The Shadow of the Fuma Clan',
  138:'Pure Betrayal, and a Fleeting Plea!', 139:'Pure Terror! The House of Orochimaru',
  140:'Two Idols Risking Their Lives: The Way a Shinobi Dies',
  141:'Reunion, and Then the Journey Onwards!',
  142:'The Three Villains from the Maximum Security Prison',
  143:'Tonton! I\'m Counting on You!', 144:'A New Squad! Two People and a Dog?!',
  145:'A New Formation: Ino–Shika–Chō!', 146:'Remaining Ambition: Orochimaru\'s Shadow',
  147:'A Clash of Fate: You Can\'t Bring Me Down!', 148:'The Search for the Rare Bikōchū Beetle',
  149:'What\'s the Difference? Don\'t All Insects Look Alike?',
  150:'A Battle of Bugs! The Deceivers and the Deceived!',
  151:'Blaze Away, Byakugan! This Is My Ninja Way!',
  152:'Funeral March for the Living', 153:'A Lesson Learned: The Iron Fist of Love!',
  154:'The Enemy of the Byakugan', 155:'The Dark Creeping Clouds',
  156:'Raiga\'s Counterattack', 157:'Run! The Curry of Life!',
  158:'Follow My Lead! The Great Survival Challenge',
  159:'The Bounty Hunter from the Wilderness',
  160:'Hunt or Be Hunted?! Showdown at the O.K. Temple!',
  161:'The Appearance of Strange Visitors', 162:'The Cursed Warrior',
  163:'The Tactician\'s Intent', 164:'Too Late for Help',
  165:'The Death of Naruto', 166:'When Time Stands Still',
  167:'When Egrets Flap Their Wings',
  168:'Mix It, Stretch It, Boil It Up! Burn Copper Pot, Burn!',
  169:'Remembrance: The Lost Page', 170:'The Closed Door',
  171:'Infiltration: The Set-Up!', 172:'Despair: A Fractured Heart',
  173:'Battle at Sea: The Power Unleashed!',
  174:'Impossible! Celebrity Ninja Art: Money Style Jutsu!',
  175:'The Treasure Hunt Is On!',
  176:'Run, Dodge, Zigzag! Chase or Be Chased!', 177:'Please, Mr. Postman!',
  178:'Encounter! The Boy with a Star\'s Name', 179:'The Remembered Lullaby',
  180:'Hidden Jutsu! The Price of Ninja Art: Kujaku',
  181:'Hoshikage: The Buried Truth', 182:'Reunion: The Remaining Time',
  183:'The Star\'s Radiance', 184:'Kiba\'s Long Day',
  185:'A Legend from the Hidden Leaf: The Onbaa!', 186:'Laughing Shino',
  187:'Open for Business! The Leaf Moving Service',
  188:'The Mystery of the Targeted Merchants',
  189:'A Limitless Supply of Ninja Tools',
  190:'The Byakugan Sees the Blind Spot!',
  191:'Forecast: Death! Cloudy with Chance of Sun!',
  192:'Ino Screams! Chubby Paradise!',
  193:'Viva Dojo Challenge! Youth Is All About Passion!',
  194:'The Mysterious Curse of the Haunted Castle',
  195:'The Third Super-Beast!', 196:'Hot-Blooded Confrontation: Student vs. Sensei',
  197:'Crisis: The Hidden Leaf 11 Gather!',
  198:'The Anbu Gives Up? Naruto\'s Recollection',
  199:'The Missed Target', 200:'The Powerful Helper',
  201:'Multiple Traps! Countdown to Destruction',
  202:'The Top 5 Ninja Battles!',
  203:'Kurenai\'s Decision: Team 8 Left Behind',
  204:'Yakumo\'s Sealed Power',
  205:'Kurenai\'s Top Secret Mission: The Promise with the Third Hokage',
  206:'Genjutsu or Reality?', 207:'The Supposed Sealed Ability',
  208:'The Weight of the Prized Artifact!', 209:'The Enemy: Ninja Dropouts',
  210:'The Bewildering Forest', 211:'Memory of Flames',
  212:'To Each His Own Path', 213:'Vanished Memories',
  214:'Bringing Back Reality', 215:'A Past to Be Erased',
  216:'The Targeted Shukaku', 217:'Sand Alliance with the Leaf Shinobi',
  218:'Sealed Sand: The Counterattack!', 219:'The Ultimate Weapon Reborn',
  220:'Departure and Arrival'
};

const EP_TITLES_S = {
  1:'Homecoming', 2:'The Akatsuki Makes Its Move', 3:'The Results of Training',
  4:'The Jinchuriki of the Sand', 5:'The Kazekage Stands Tall', 6:'Mission Cleared!',
  7:'Run, Kankuro', 8:'Team Kakashi, Deployed', 9:'The Jinchuriki\'s Tears',
  10:'Sealing Jutsu: Nine Phantoms', 11:'The Medical Ninja\'s Student', 12:'The Retired Granny\'s Determination',
  13:'A Meeting With Destiny', 14:'Naruto\'s Growth', 15:'The Secret Weapon is Called...',
  16:'The Secret of Jinchuriki', 17:'The Death of Gaara!', 18:'Charge Tactic! Button Hook Entry!!',
  19:'Traps Activate! Team Guy\'s Enemy', 20:'Hiruko vs. Two Kunoichi!',
  21:'Sasori\'s Real Face', 22:'Chiyo\'s Secret Skills', 23:'Father and Mother',
  24:'The Third Kazekage', 25:'Three Minutes Between Life and Death', 26:'Puppet Fight: 10 vs. 100!',
  27:'Impossible Dream', 28:'Beasts! Foolish Beasts!', 29:'Kakashi Enlightened!',
  30:'Aesthetics of an Instant', 31:'The Legacy!', 32:'Return of the Kazekage',
  33:'The New Target', 34:'Bonds', 35:'The Vessel', 36:'The Fake Smile',
  37:'Untitled', 38:'Simulation', 39:'The Tenchi Bridge', 40:'Nine-Tails Unleashed',
  41:'The Top-Secret Mission Begins', 42:'Orochimaru vs. Jinchuriki', 43:'Sakura\'s Determination',
  44:'The Secret of the Battle!', 45:'An Eternal Battle!?', 46:'The Unfinished Page',
  47:'Infiltration: The Den of the Snake!', 48:'Bonds', 49:'Something Important…',
  50:'The Picture Book\'s Story', 51:'Reunion', 52:'The Power of Uchiha',
  53:'Title', 54:'Nightmare', 55:'Wind', 56:'Writhing', 57:'Deception',
  58:'The Man Who Knows the Truth', 59:'A New Enemy', 60:'Impermanence',
  61:'Contact', 62:'Teammate', 63:'The Two Kings', 64:'Jet-Black Signal Fire',
  65:'Lockdown of Darkness', 66:'Confessions', 67:'Everyone\'s Struggle to the Death',
  68:'Moment of Awakening', 69:'Despair', 70:'Resonance', 71:'My Friend',
  72:'The Quietly Approaching Threat', 73:'Akatsuki\'s Invasion', 74:'Under the Starry Sky',
  75:'Tales of a Gutsy Ninja: Jiraiya Ninja Scrolls — Part 1', 76:'Tales of a Gutsy Ninja: Jiraiya Ninja Scrolls — Part 2',
  77:'The Whirlpool Country Shinobi — Uzumaki Naruto!', 78:'The Reversed Seal',
  79:'The Mystery of Tobi', 80:'Searching for the Forbidden Word', 81:'Sad News',
  82:'Team 10', 83:'Target: Nine-Tails', 84:'Judgment', 85:'The Terrifying Secret',
  86:'Ao\'s Chase', 87:'The Rogue Ninja Mukade!', 88:'Approaching Shadows',
  89:'The Price of Power', 90:'A Shinobi\'s Determination',
  91:'Orochimaru\'s Hideout Discovered', 92:'Encounter',
  93:'Connecting Hearts', 94:'A Night of Rain', 95:'The Two Charms',
  96:'The Unseeing Enemy', 97:'The Labyrinth of Distorted Reflection',
  98:'The Target Appears', 99:'The Rampaging Tailed Beast',
  100:'Inside the Mist', 101:'Everyone\'s Feelings', 102:'Regroup!',
  103:'The Four-Corner Sealing Barrier', 104:'Breaking the Crystal Style',
  105:'The Battle Over the Barrier', 106:'Red Camellia',
  107:'Strange Bedfellows', 108:'Guidepost of the Camellia',
  109:'Counterattack of the Curse Mark', 110:'Memory of Guilt',
  111:'Shattered Promise', 112:'A Place to Return To',
  113:'The Serpent\'s Pupil', 114:'Eye of a Hawk',
  115:'Zabuza\'s Blade', 116:'Guardian of the Iron Wall',
  117:'Jugo of the Northern Hideout', 118:'Formation!',
  119:'Kakashi Chronicles: A Boy\'s Life on the Battlefield, Part 1',
  120:'Kakashi Chronicles: A Boy\'s Life on the Battlefield, Part 2',
  121:'Assemble', 122:'The Hunt', 123:'Clash!', 124:'Art',
  125:'Disappearance', 126:'Twilight',
  127:'Tales of a Gutsy Ninja ~Jiraiya Ninja Scroll~ Part 1',
  128:'Tales of a Gutsy Ninja ~Jiraiya Ninja Scroll~ Part 2',
  129:'Infiltrate! The Village Hidden in the Rain',
  130:'The Man Who Became God', 131:'Honoured Sage Mode!',
  132:'In Attendance, the Six Paths of Pain',
  133:'The Tale of Jiraiya the Gallant', 134:'Banquet Invitation',
  135:'The Longest Moment',
  136:'The Light and Dark of the Mangekyō Sharingan',
  137:'Amaterasu!', 138:'The End', 139:'The Mystery of Tobi',
  140:'Fate', 141:'Truth',
  142:'Battle of Valley of Clouds and Lightning',
  143:'The Eight-Tails vs. Sasuke',
  144:'Wanderer', 145:'Successor of the Forbidden Jutsu',
  146:'The Successor\'s Wish', 147:'Rogue Ninja\'s Past',
  148:'Heir to Darkness', 149:'Separation',
  150:'The Forbidden Jutsu Released', 151:'Master and Student',
  152:'Somber News', 153:'Following the Master\'s Shadow', 154:'Decryption',
  155:'The First Challenge', 156:'Surpassing the Master', 157:'Assault on the Leaf Village!',
  158:'Power to Believe', 159:'Pain vs. Kakashi', 160:'Mystery of Pain',
  161:'Surname Is Sarutobi! Given Name, Konohamaru!', 162:'Pain to the World',
  163:'Explode! Sage Mode', 164:'Danger! Sage Mode Limit Reached', 165:'Nine-Tails, Captured!',
  166:'Confession', 167:'Planetary Devastation', 168:'The Fourth Hokage',
  169:'The Two Students', 170:'Big Adventure! The Quest for the Fourth Hokage\'s Legacy — Part 1',
  171:'Big Adventure! The Quest for the Fourth Hokage\'s Legacy — Part 2',
  172:'Meeting', 173:'The Origin of Pain', 174:'Naruto\'s Plea',
  175:'Hero of the Hidden Leaf',
  176:'Rookie Instructor Iruka', 177:'Iruka\'s Ordeal',
  178:'Iruka\'s Decision', 179:'Kakashi Hatake, the Jonin in Charge',
  180:'Inari\'s Courage Put to the Test',
  181:'Naruto\'s School of Revenge', 182:'Gaara\'s Bond',
  183:'Naruto: Outbreak', 184:'Deploy! Team Tenten',
  185:'Animal District', 186:'Ah, the Medicine of Youth',
  187:'Gutsy Master and Student: The Training',
  188:'Record of the Ninja Gutsy Master and Student',
  189:'Sasuke\'s Paw Encyclopedia', 190:'Naruto and the Old Soldier',
  191:'Kakashi Love Song', 192:'Neji Chronicles',
  193:'The Man Who Died Twice', 194:'The Worst Three-Legged Race',
  195:'Team 10\'s Teamwork', 196:'Drive Towards Darkness',
  197:'The Sixth Hokage Danzo', 198:'Five Kage Summit\'s Eve', 199:'Enter the Five Kage!',
  200:'Naruto\'s Plea', 201:'Madara Uchiha', 202:'Racing Lightning',
  203:'Sasuke\'s Ninja Way', 204:'Power of the Five Kage!', 205:'Declaration of War',
  206:'Sakura\'s Feelings', 207:'The Tailed Beast vs. The Tailless Tailed Beast',
  208:'As One\'s Friend', 209:'Danzo\'s Right Arm', 210:'The Forbidden Visual Jutsu',
  211:'Danzo Shimura', 212:'Sakura\'s Resolve', 213:'Lost Bonds', 214:'The Burden',
  215:'Two Fates', 216:'High-Level Shinobi', 217:'The Island Turtle Appears!', 218:'A Boat to Live On',
  219:'Paradox', 220:'Killer Bee and Motoi', 221:'The Ace in the Hole',
  222:'The Five Great Nations Mobilize',
  223:'The Young Man and the Sea', 224:'The Ninja of Benisu',
  225:'The Cursed Ghost Ship', 226:'Battleship Island',
  227:'The Forgotten Island', 228:'Fight! Rock Lee!',
  229:'Eat or Die! Mushrooms from Hell!',
  230:'Revenge of the Shadow Clones', 231:'The Closed Route',
  232:'The Girls\' Get-Together', 233:'Naruto\'s Imposter',
  234:'Naruto\'s Favorite Student',
  235:'The Kunoichi of Nadeshiko Village',
  236:'Friends You Can Count On',
  237:'Ah, My Hero Lady Tsunade!', 238:'Sai\'s Day Off',
  239:'The Legendary Ino-Shika-Cho Trio',
  240:'Kiba\'s Determination', 241:'Kakashi, My Eternal Rival!',
  242:'Naruto\'s Vow',
  243:'Land Ahoy! Is this the Paradise Island?',
  244:'Battleship Island!', 245:'The Terrifying Experiment', 246:'Ah, My Hero Lady Tsunade!',
  247:'Target: Kurosuki Family Removal Mission', 248:'Obito and Rin', 249:'As a Taijutsu User',
  250:'Battle in Paradise! Odd Beast vs. The Monster!', 251:'The Man Named Kisame',
  252:'The Angelic Herald of Death', 253:'The Bridge to Peace', 254:'The Super Secret S-Rank Mission',
  255:'Power — Episode 1', 256:'Power — Episode 2',
  257:'Meeting', 258:'The Beginning of the Battle', 259:'Rift', 260:'Qualified',
  261:'For My Friend', 262:'War Begins!', 263:'Sai and Shin', 264:'The Secret of the Four-Eyes',
  265:'Partners', 266:'The First and Last Opponent', 267:'The Brilliant Military Advisor of the Hidden Leaf',
  268:'Battleground!', 269:'Forbidden Words', 270:'Golden Bonds', 271:'Road to Sakura',
  272:'Mifune vs. Hanzo', 273:'True Kindness', 274:'The Complete Ino-Shika-Cho Formation!',
  275:'A Message from the Heart', 276:'Attack! Fury of the Rasengan!', 277:'Climb up! Rock Lee',
  278:'Secrets of the Reanimation Jutsu', 279:'White Zetsu\'s Trap', 280:'Aesthetics of an Instant',
  281:'The Allied Mom Force!!', 282:'The Pa and the Ma', 283:'Two Suns', 284:'The Helmet Splitter: Jinin Akebino!',
  285:'User of the Scorch Style: Pakura of the Sand!', 286:'Things You Can\'t Get Back',
  287:'One Worth Betting On', 288:'Danger: Jinpachi and Kushimaru!',
  289:'The Lightning Blade: Ameyuri Ringo!',
  290:'Power — Episode 1', 291:'Power — Episode 2',
  292:'Power — Episode 3', 293:'Power — Episode 4',
  294:'Power — Episode 5', 295:'Power — Episode Final',
  296:'Naruto Enters the Battle!', 297:'A Father\'s Hope, A Mother\'s Love',
  298:'Contact with the Nine-Tails', 299:'The Acknowledged One',
  300:'The Steam Imp', 301:'Paradox', 302:'Terror: The Steam Imp',
  303:'Ghosts from the Past', 304:'The Underworld Transfer Jutsu',
  305:'The Vengeful', 306:'The Heart\'s Eye', 307:'Fade into the Moonlight',
  308:'Crescent Moon Dance', 309:'An A-Rank Mission: The Contest', 310:'The Ninja of Benisu',
  311:'Prologue of Road to Ninja', 312:'The Old Master and the Dragon\'s Eye',
  313:'Rain Followed by Snow, with Some Lightning', 314:'The Sad Sun Shower',
  315:'Lingering Snow', 316:'The Reanimated Allied Forces', 317:'Shino vs. Torune!',
  318:'A Hole in the Heart: The Other Jinchuriki', 319:'The Soul That Dwells in a Puppet',
  320:'Risking It All to Win', 321:'Reinforcements Arrive', 322:'Madara Uchiha',
  323:'The Risks of Edo Tensei', 324:'The Unbreakable Mask and the Shattered Bubble',
  325:'Jinchuriki vs. Jinchuriki!!', 326:'Four Tails, the King of Sage Monkeys',
  327:'Nine-Tails', 328:'Kurama', 329:'Two-Man Team', 330:'The Promise of Victory',
  331:'Eyes That See in the Dark', 332:'A Will of Stone', 333:'The Three-Minute Limit',
  334:'The Risks of Edo Tensei', 335:'To Each Their Own Leaf', 336:'Mysterious Masked Man',
  337:'Izanagi and Izanami', 338:'Izanami Activated!', 339:'I Will Love You Always',
  340:'Reanimation Jutsu: Release!', 341:'Orochimaru\'s Return', 342:'The Secret of the Transportation Technique',
  343:'Who Are You?', 344:'Obito and Madara', 345:'I\'m in Hell', 346:'World of Dreams',
  347:'Creeping Shadow', 348:'The New Tailed Beast-Bomb', 349:'A Hole in the Heart: The Other Jinchuriki',
  350:'Minato\'s Death', 351:'The Sage of Six Paths', 352:'The Eternal Kaleidoscope',
  353:'Jugo\'s Long Travels', 354:'The New Three-Way Deadlock', 355:'Kakashi\'s Resolve',
  356:'The Directive to Take the Nine-Tails', 357:'An Opening', 358:'The Mask Crumbles',
  359:'Obito Uchiha', 360:'Ninja Alliance — Shattered!', 361:'Kakashi\'s Conclusion',
  362:'The Allied Shinobi Forces Technique', 363:'The Ties That Bind',
  364:'Those Who Dance in the Shadows', 365:'The All-Knowing',
  366:'Hashirama and Madara', 367:'Warring States Period',
  368:'My True Dream', 369:'Sasuke\'s Answer', 370:'Hole',
  371:'Something to Fill the Hole', 372:'Team 7 Assemble!',
  373:'The New Three-Way Deadlock', 374:'Kakashi vs. Obito',
  375:'The Directive to Take the Nine-Tails!',
  376:'Naruto vs. Mecha Naruto',
  377:'The Jinchuriki of the Ten Tails', 378:'An Opening',
  379:'The Adored Elder Sister',
  380:'The Day Naruto Was Born', 381:'The Exploding Human', 382:'A Fabricated Past',
  383:'Pursuing Hope', 384:'A Heart Filled with Coexistence', 385:'Obito Uchiha',
  386:'I\'m Always Watching', 387:'The Promise That Was Kept', 388:'My Will Is',
  389:'The Adored Elder Sister', 390:'Hanabi\'s Decision',
  391:'Madara Uchiha Returns', 392:'The Hidden Heart', 393:'A True Ending',
  394:'The New Chūnin Exams', 395:'The Chūnin Exams Begin',
  396:'The Three Questions', 397:'One Worthy as a Leader',
  398:'The Night Before the Second Exam',
  399:'Demon Desert Survival', 400:'As a Taijutsu User',
  401:'The Ultimate', 402:'Escape vs. Pursuit',
  403:'Unwavering Gutsiness', 404:'Tenten\'s Troubles',
  405:'The Imprisoned Pair', 406:'The Place Where I Belong',
  407:'The Yamanaka Clan: Secret Ninjutsu', 408:'The Cursed Puppet',
  409:'Their Backs', 410:'The Hidden Plot Set Into Motion',
  411:'The Targeted Tailed Beast', 412:'Neji\'s Judgment',
  413:'Hopes Entrusted to the Future',
  414:'One Heart', 415:'The Two Mangekyō', 416:'The Formation of Team Minato',
  417:'The Dual Uchiha',
  418:'The Blue Beast vs. Six Paths Madara', 419:'Overflowing Light', 420:'The Eight Inner Gates Formation',
  421:'The Allied Shinobi Forces Jutsu',
  422:'The Sage of Six Paths', 423:'The Ones Who Will Inherit',
  424:'To Rise Up', 425:'Naruto and Sasuke',
  427:'To the Dreamworld', 428:'Where Tenten Belongs',
  429:'Killer B Rappūden: Part 1', 430:'Killer B Rappūden: Part 2',
  431:'To See That Smile, Just One More Time',
  432:'The Loser Ninja', 433:'The Search Mission',
  434:'Team Jiraiya', 435:'Order of Priority',
  436:'The Masked Man', 437:'The Sealed Power',
  438:'The Rules or a Comrade', 439:'The Child of Prophecy',
  440:'The Caged Bird', 441:'Returning Home',
  442:'The Mutual Path', 443:'The Difference in Power',
  444:'Leaving the Village', 445:'Pursuers',
  446:'Collision', 447:'Another Moon',
  448:'Comrade', 449:'The Shinobi Unite',
  450:'Rival', 451:'Birth and Death',
  452:'The Genius', 453:'The Pain of Living',
  454:'Shisui\'s Request', 455:'Moonlit Night',
  456:'The Darkness of the Akatsuki', 457:'Partner',
  458:'The Ten-Tails\' Jinchuriki', 459:'She of the Beginning', 460:'Kaguya\'s Dimensions',
  461:'Orochimaru\'s Test Subjects', 462:'The Genius', 463:'The Sharingan Revived',
  464:'Ninshū: The Ninja Creed', 465:'The Ninshū World', 466:'The Reason for Reincarnation',
  467:'You\'ll Be My Backup', 468:'The Seal of Reconciliation',
  469:'Connecting Thoughts', 470:'The Two of Them… Always',
  471:'You Better...', 472:'The Sharingan Revived',
  473:'Congratulations', 474:'The Valley of the End',
  475:'The Final Battle', 476:'Naruto and Sasuke',
  477:'The Unison Sign', 478:'Naruto Uzumaki!!',
  479:'Naruto ・ Hinata',
  480:'Naruto Uzumaki!!', 481:'Sasuke Uchiha!!', 482:'Sakura Uchiha!!',
  483:'Gaara and Shukaku', 484:'Sai and Shin', 485:'Sasuke\'s Story — Sunrise Part 1',
  486:'Sasuke\'s Story — Sunrise Part 2', 487:'Shikamaru\'s Story Part 1',
  488:'Shikamaru\'s Story Part 2', 489:'Shikamaru\'s Story Part 3',
  490:'Temari\'s Story', 491:'Konoha Hiden Part 1', 492:'Konoha Hiden Part 2',
  493:'Konoha Hiden Part 3', 494:'The Last Mission', 495:'Wedding Invitation',
  496:'Cloudy with Chance of Tears', 497:'The Night Before the Wedding',
  498:'The Outcome of the Vote', 499:'Connecting Feelings', 500:'The Message',
};

const ARCS = {
  // ---- NARUTO ORIGINAL ----
  0: { series: 'naruto', eps: range(1,19,'canon') },
  1: { series: 'naruto', eps: [...range(20,25,'canon'), ...range(26,26,'filler'), ...range(27,67,'canon')] },
  2: { series: 'naruto', eps: range(68,80,'canon') },
  3: { series: 'naruto', eps: [...range(81,96,'canon'), ...range(97,97,'filler'), ...range(98,100,'canon')] },
  4: { series: 'naruto', eps: range(101,106,'filler') },
  5: { series: 'naruto', eps: range(107,135,'canon') },
  6: { series: 'naruto', eps: [...range(136,140,'filler'), ...range(141,142,'canon')] },
  7: { series: 'naruto', eps: range(143,219,'filler') },
  8: { series: 'naruto', eps: [{ id:'naruto-220', num:220, title:'The Top-Secret Mission Begins', type:'canon' }] },

  // ---- MOVIES ----
  m1: { series: 'movies', eps: [
    { id:'movie-1', num:'Film 1', title:'Ninja Clash in the Land of Snow (2004)', type:'movie' },
    { id:'movie-2', num:'Film 2', title:'Legend of the Stone of Gelel (2005)', type:'movie' },
    { id:'movie-3', num:'Film 3', title:'Guardians of the Crescent Moon Kingdom (2006)', type:'movie' },
  ]},
  m2: { series: 'movies', eps: [
    { id:'movie-4', num:'Film 4', title:'Shippuden Movie 1 — Shippuden (2007)', type:'movie' },
    { id:'movie-5', num:'Film 5', title:'Shippuden Movie 2 — Bonds (2008)', type:'movie' },
    { id:'movie-6', num:'Film 6', title:'Shippuden Movie 3 — Will of Fire (2009)', type:'movie' },
    { id:'movie-7', num:'Film 7', title:'Shippuden Movie 4 — The Lost Tower (2010)', type:'movie' },
    { id:'movie-8', num:'Film 8', title:'Shippuden Movie 5 — Blood Prison (2011)', type:'movie' },
    { id:'movie-9', num:'Film 9', title:'Shippuden Movie 6 — Road to Ninja (2012)', type:'movie' },
  ]},
  m3: { series: 'movies', eps: [
    { id:'movie-10', num:'Film 10', title:'The Last: Naruto the Movie (2014)', type:'movie' },
    { id:'movie-11', num:'Film 11', title:'Boruto: Naruto the Movie (2015)', type:'movie' },
  ]},

  // ---- SHIPPUDEN ----
  s1:  { series: 'shippuden', eps: shipRange(1,32,'canon') },
  s3:  { series: 'shippuden', eps: shipRange(33,53,'canon') },
  s2:  { series: 'shippuden', eps: [...shipRange(54,56,'canon'), ...shipRange(57,71,'filler')] },
  s4:  { series: 'shippuden', eps: shipRange(72,90,'canon') },
  s5:  { series: 'shippuden', eps: shipRange(91,112,'filler') },
  s6:  { series: 'shippuden', eps: shipRange(113,143,'canon') },
  s7:  { series: 'shippuden', eps: shipRange(144,151,'filler') },
  s8:  { series: 'shippuden', eps: [...shipRange(152,169,'canon'), ...shipRange(170,171,'filler'), ...shipRange(172,175,'canon')] },
  s10: { series: 'shippuden', eps: shipRange(176,196,'filler') },
  s9:  { series: 'shippuden', eps: shipRange(197,222,'canon') },
  s11: { series: 'shippuden', eps: shipRange(243,256,'canon') },
  s12: { series: 'shippuden', eps: shipRange(223,242,'filler') },
  s13: { series: 'shippuden', eps: [
    ...shipRange(257,260,'filler'),
    ...shipRange(261,270,'canon'),
    ...shipRange(271,271,'filler'),
    ...shipRange(272,278,'canon'),
    ...shipRange(279,281,'filler'),
    ...shipRange(282,283,'canon'),
    ...shipRange(284,289,'filler'),
  ]},
  s14: { series: 'shippuden', eps: shipRange(290,295,'filler') },
  s15a: { series: 'shippuden', eps: [...shipRange(296,302,'canon'), ...shipRange(303,320,'filler')] },
  s15b: { series: 'shippuden', eps: [...shipRange(321,346,'canon'), ...shipRange(347,348,'filler')] },
  s15c: { series: 'shippuden', eps: shipRange(349,361,'filler') },
  s15d: { series: 'shippuden', eps: [...shipRange(362,375,'canon'), ...shipRange(376,377,'filler')] },
  s15e: { series: 'shippuden', eps: [...shipRange(378,387,'canon'), ...shipRange(388,390,'filler'), ...shipRange(391,393,'canon')] },
  s15f: { series: 'shippuden', eps: shipRange(394,413,'filler') },
  s15g: { series: 'shippuden', eps: [
    ...shipRange(414,415,'canon'),
    ...shipRange(416,417,'filler'),
    ...shipRange(418,421,'canon'),
    ...shipRange(422,423,'filler'),
    ...shipRange(424,426,'canon'),
    ...shipRange(427,431,'filler'),
  ]},
  s16: { series: 'shippuden', eps: shipRange(432,450,'filler') },
  s17: { series: 'shippuden', eps: [...shipRange(451,463,'canon'), ...shipRange(464,468,'filler')] },
  s18: { series: 'shippuden', eps: shipRange(469,479,'canon') },
  s19: { series: 'shippuden', eps: [...shipRange(480,483,'filler'), ...shipRange(484,500,'canon')] },
};


function range(a, b, type) {
  const arr = [];
  for (let i = a; i <= b; i++) {
    arr.push({ id:`naruto-${i}`, num:i, title: EP_TITLES_N[i] || `Episode ${i}`, type });
  }
  return arr;
}

function shipRange(a, b, type) {
  const arr = [];
  for (let i = a; i <= b; i++) {
    arr.push({ id:`shippuden-${i}`, num:i, title: EP_TITLES_S[i] || `Shippuden Episode ${i}`, type });
  }
  return arr;
}

// ============================================================
// STATE
// ============================================================
let watched = {};
try { watched = JSON.parse(localStorage.getItem('naruto-watched') || '{}'); } catch(e) {}
let currentFilter = 'all';

function save() {
  try { localStorage.setItem('naruto-watched', JSON.stringify(watched)); } catch(e) {}
}
